spring.application.name=demo

#
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=Capl


spring.data.mongodb.uri=mongodb+srv://ayushcoder69_db_user:GO95OyGhEgaGGpkf@userdata.vvvs2au.mongodb.net/

spring.data.mongodb.database=Capl
spring.data.mongodb.auto-index-creation=true